### PR TITLE
Daemon build placeholders added for obj/consensus & obj/wallet.

### PR DESCRIPTION
**Pull request by CryptoDJ**
This commit might help your Travis Ci daemon build by adding the obj/consensus and obj/wallet.  Those directories are needed for the daemon build and without them, it can't compile.  

Also, try using these commands to build the daemon and qt wallet on Travis Ci:

Daemon:
cd DarkSilk-Release-Candidate/src/secp256k1 && ./autogen.sh && ./configure --enable-module-recovery && make && cd .. && sudo make -f makefile.unix USE_UPNP=0

Qt Wallet:
cd DarkSilk-Release-Candidate && qmake -qt=qt5 "USE_QRCODE=1" "USE_NATIVE_I2P=1" && make

### CODE REVIEW

**Comment by empinel** [comment]
I just commited that. Thanks!

**Comment by empinel** [comment]
AFAIK, The QMake Command Automagically Compiles SECP256k1

**Comment by CryptoDJ** [comment]
just make sure you have are using Qt 5:   qmake -qt=qt5

**Comment by CryptoDJ** [comment]
Daemon build fails for me.  Same error as Travis.

**Comment by empinel** [comment]
https://github.com/empinel/DarkSilk-Release-Candidate/blob/master/src/makefile.unix

**Comment by empinel** [comment]
You can see that there are obj/wallet/db.o references

**Pull request merged**
